#ifndef __STRINGS_H__
#define __STRINGS_H__


typedef enum
{
	STR_NULL,
	STR_HR,
	STR_PVCs,
	STR_SPO2,
	STR_PR,
	STR_RESP,
	STR_TEMP,
	STR_TEMP_T1,	
	STR_TEMP_T2,
	STR_TEMP_TD,
	STR_NIBP,

	STR_ADULT,
	STR_PEDIA,
	STR_NEONATE,

	STR_SEX,
	STR_PATIENT_TYPE,
	STR_BIRTHDAY,
	STR_STATURE,
	STR_AVOIRDUPOIS,
	STR_LINE,
	STR_MALE,
	STR_FEMALE,
	STR_YES,
	STR_NO,

	STR_BLOOD_A,
	STR_BLOOD_B,
	STR_BLOOD_AB,
	STR_BLOOD_O,

	STR_NOTCH_ON,
	STR_NOTCH_OFF,

	STR_UNIT_TEMP_C,
	STR_UNIT_MMHG,
	STR_UNIT_PERCENTAGE,
	STR_UNIT_BPM,
	STR_UNIT_KG,
	STR_UNIT_LB,
	STR_UNIT_M,
	STR_UNIT_CM,

	STR_WAVE_NAME_SPO2,
	STR_WAVE_NAME_ECG_II,
	STR_WAVE_NAME_ECG_I,
	STR_WAVE_NAME_ECG_III,
	STR_WAVE_NAME_ECG_AVL,
	STR_WAVE_NAME_ECG_AVF,
	STR_WAVE_NAME_ECG_AVR,
	STR_WAVE_NAME_ECG_V,
	STR_WAVE_NAME_RESP,

	STR_ST_ANALYSIS_SETUP_DLG_S_STII,

	STR_ECG_LEAD_I,
	STR_ECG_LEAD_II,
	STR_ECG_LEAD_III,
	STR_ECG_LEAD_AVR,
	STR_ECG_LEAD_AVL,
	STR_ECG_LEAD_AVF,
	STR_ECG_LEAD_V,
	STR_ECG_SETUP_DLG_LB_FILTER_MONITOR,

	STR_SETUP_DLG_TITLE,
	STR_SETUP_DLG_SURNAME,
	STR_SETUP_DLG_NAME,
	STR_SETUP_DLG_CASE,
	STR_SETUP_DLG_ADMIT_DATE,
	STR_SETUP_DLG_BLOOD,
	
	STR_ECG_ST_OFF,

	STR_TREND_VITALS_NAME,
	STR_TREND_RR_TITLE,
	STR_TREND_HR_TITLE,
	STR_TREND_SPO2_TITLE,

	STR_TREND_PRESSURES_NAME,
	STR_TREND_PRESSURES_SYS_TITLE,
	STR_TREND_PRESSURES_DIA_TITLE,
	STR_TREND_PRESSURES_MEAN_TITLE,

	STR_TIME_SCALE_BAR_BACKWARD,
	STR_TIME_SCALE_BAR_FAST_BACKWARD,
	STR_TIME_SCALE_BAR_FORWARD,
	STR_TIME_SCALE_BAR_FAST_FORWARD,

	//ABOUT
	STR_ABOUT_SOFTWARE,
	STR_ABOUT_SOFT_NAME,
	STR_ABOUT_CROSS_PLATFORM,
	STR_ABOUT_WORK_CONDITION,
	STR_ABOUT_SOURCE,
	STR_ABOU_AUTHOR,
	STR_ABOUT_EMAIL,

	STR_END,
}E_STRINGS;

#endif
